version: '2'
services:
  user-gateway-ms:
    image: user-gateway-ms:0.0.1
    container_name: user-gateway-ms
    ports:
      - "8080:8080"
      - "7000:7000"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7000